name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/LICENSE"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: false
          format: false
          breaking: false
          push: true
          archive: false
          pr_comment: false
          push_create_visibility: public
