name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/LICENSE"
  delete:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: ${{ github.event_name == 'push' }}
          format: false
          breaking: ${{ github.event_name == 'push' }}
          push: ${{ github.event_name == 'push' }}
          archive: ${{ github.event_name == 'delete' }}
          pr_comment: false
          push_create_visibility: public
